export const storyItemTypes = {
  FETCH_STORY_ITEMS_START: "FETCH STORY ITEMS START",
  FETCH_STORY_ITEMS_SUCCESS: "FETCH STORY ITEMS SUCCESS",
  FETCH_STORY_ITEMS_FAIL: "FETCH STORY ITEMS FAIL",
  SET_ACTIVE_PAGE_IDS: "SET ACTIVE PAGE IDS",
  SAVE_STORY_URL: "SAVE STORY URL",
};
