export const userTypes = {
  REGISTER_USER_START: "REGISTER USER ITEMS START",
  REGISTER_USER_SUCCESS: "REGISTER USER SUCCESS",
  REGISTER_USER_FAIL: "REGISTER USER FAIL",
  LOGIN_USER_START: "LOGIN USER START",
  LOGIN_USER_SUCCESS: "LOGIN USER SUCCESS",
  LOGIN_USER_FAIL: "LOGIN USER FAIL",
};
